# -*- coding: utf-8 -*-
"""电影评分.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EmRHEmWvQngK5rKeanZn1KWmAU4igKp7
"""

import pandas as pd
import numpy as np

df = pd.read_csv('cleaned_reviews_data.csv')

df.head()

df.columns

print(df.shape)

print(df[['movie_name', 'genres', 'Ratings']].isnull().sum())

df['genres'].head(10)

genre_df = df.copy()

genre_df['genres'] = genre_df['genres'].str.replace('[', '', regex=False)

genre_df['genres'] = genre_df['genres'].str.replace(']', '', regex=False)

genre_df['genres'] = genre_df['genres'].str.replace("'", '', regex=False)

genre_df['genres'] = genre_df['genres'].str.split(',')

genre_df = genre_df.explode('genres')

genre_df['genres'] = genre_df['genres'].str.strip()

print(genre_df[['movie_name', 'genres']].head(20))

genre_review_count = genre_df.groupby('genres').size()
genre_review_count = genre_review_count.reset_index()
genre_review_count.columns = ['genre', 'review_count']

genre_review_count = genre_review_count.sort_values(
    by='review_count',
    ascending=False
)

genre_review_count.head(10)

genre_median = genre_review_count['review_count'].median()

print("Genre Review Count Median:", genre_median)

high_engagement_genres = genre_review_count[
    genre_review_count['review_count'] > genre_median
]

high_engagement_genres

selected_genres = high_engagement_genres['genre'].tolist()

filtered_genre_df = genre_df[
    genre_df['genres'].isin(selected_genres)
]

genre_avg_rating = filtered_genre_df.groupby(
    'genres'
)['Ratings'].mean()

genre_avg_rating = genre_avg_rating.reset_index()

genre_avg_rating.columns = [
    'genre',
    'average_rating'
]

genre_avg_rating = genre_avg_rating.sort_values(
    by='average_rating',
    ascending=False
)

print(genre_avg_rating)

top_genre = genre_avg_rating.iloc[0]

print("Highest-Rated High-Engagement Genre:")
print(top_genre)

"""crime"""

crime_df = genre_df[
    genre_df['genres'] == 'Crime'
]

total_crime_movies = crime_df['movie_name'].nunique()

print("Total Number of Crime Movies:")
print(total_crime_movies)

crime_movie_names = crime_df['movie_name'].unique()

print(crime_movie_names)

crime_movie_review_count = crime_df.groupby(
    'movie_name'
).size()

crime_movie_review_count = crime_movie_review_count.reset_index()

crime_movie_review_count.columns = [
    'movie_name',
    'review_count'
]

crime_movie_review_count = crime_movie_review_count.sort_values(
    by='review_count',
    ascending=False
)

print(crime_movie_review_count)

high_engagement_crime_movies = crime_movie_review_count[

    crime_movie_review_count['review_count']
    > 14
]

print(high_engagement_crime_movies)

crime_df = genre_df[
    genre_df['genres'] == 'Crime'
]

print(crime_df.head())

crime_movie_review_count = crime_df.groupby(
    'movie_name'
).size()

crime_movie_review_count = crime_movie_review_count.reset_index()

crime_movie_review_count.columns = [
    'movie_name',
    'review_count'
]

crime_movie_median = crime_movie_review_count[
    'review_count'
].median()

print(crime_movie_median)

high_engagement_crime_movies = crime_movie_review_count[

    crime_movie_review_count['review_count']
    > crime_movie_median
]

crime_movie_names = high_engagement_crime_movies[
    'movie_name'
].tolist()

filtered_crime_df = crime_df[
    crime_df['movie_name'].isin(crime_movie_names)
]

crime_movie_avg_rating = filtered_crime_df.groupby(
    'movie_name'
)['Ratings'].mean()

crime_movie_avg_rating = crime_movie_avg_rating.reset_index()

crime_movie_avg_rating.columns = [
    'movie_name',
    'average_rating'
]

crime_movie_avg_rating = crime_movie_avg_rating.sort_values(

    by='average_rating',

    ascending=False
)

top_10_crime_movies = crime_movie_avg_rating.head(10)

top_10_crime_movies = top_10_crime_movies.reset_index(
    drop=True
)

print(top_10_crime_movies)

bottom_10_crime_movies = crime_movie_avg_rating.tail(10)

bottom_10_crime_movies = bottom_10_crime_movies.reset_index(
    drop=True
)

print(bottom_10_crime_movies)

top_10_crime_movie_names = top_10_crime_movies[
    'movie_name'
].tolist()

bottom_10_crime_movie_names = bottom_10_crime_movies[
    'movie_name'
].tolist()


print(top_10_crime_movie_names)

print(bottom_10_crime_movie_names)

top_crime_reviews = filtered_crime_df[

    filtered_crime_df['movie_name'].isin(
        top_10_crime_movie_names
    )
]

bottom_crime_reviews = filtered_crime_df[

    filtered_crime_df['movie_name'].isin(
        bottom_10_crime_movie_names
    )
]


print(top_crime_reviews.shape)

print(bottom_crime_reviews.shape)

top_10_movies = [

    'The Promise',
    'The Girl Next Door',
    'Rampage',
    'The Fast and the Furious',
    'Happy New Year',
    'My Super Ex-Girlfriend',
    'The Thomas Crown Affair',
    'Les MisÃ©rables',
    'White Heat',
    'Wanted'
]

bottom_10_movies = [

    'The Hunters',
    'Siberia',
    'The Deal',
    'Wild Horses',
    'The Raven',
    'The Heat',
    'Crossroads',
    'Gunday',
    'Girl in Gold Boots',
    'Nightfall'
]


top_10_df = df[

    df['movie_name'].isin(top_10_movies)
]
bottom_10_df = df[

    df['movie_name'].isin(bottom_10_movies)
]

print(top_10_df[['movie_name']].drop_duplicates())
print(bottom_10_df[['movie_name']].drop_duplicates())

!pip install google-genai pandas openpyxl pydantic

import os
from google import genai

os.environ["GEMINI_API_KEY"] = "AIzaSyBbDuN-oxUPDxy84pIDZjmvA2XGjok3AHw"

client = genai.Client(api_key=os.environ["GEMINI_API_KEY"])

import pandas as pd

file_path = "/content/top_10_crime_movies.xlsx"

df = pd.read_excel(file_path)

print(df.columns)
df.head()

reviews = df["Reviews"].dropna().astype(str).drop_duplicates().tolist()

print(len(reviews))

from pydantic import BaseModel, Field
from typing import List, Literal

class KeywordPhrase(BaseModel):
    phrase: str = Field(description="A useful content-related keyword phrase, preferably 2-4 words.")

    category: Literal[
        "genre_element",
        "story_element",
        "pacing",
        "suspense",
        "character",
        "acting",
        "realism",
        "emotion",
        "production",
        "audience_engagement",
        "hybrid_genre"
    ]

    reason: str = Field(
        description="Why this phrase is useful for content planning."
    )


class KeywordResult(BaseModel):
    phrases: List[KeywordPhrase]


def extract_useful_phrases_with_gemini(review_batch):

    reviews_text = "\n\n---\n\n".join(review_batch)

    prompt = f"""
You are a professional content analyst for a streaming company.

Task:
Extract useful keyword phrases from the following crime movie reviews.

Focus on phrases that can help with content planning, especially:
- genre elements
- story elements
- pacing
- suspense
- plot structure
- character development
- acting / performance
- realism
- emotional tone
- audience engagement
- production quality
- hybrid genre elements

Avoid:
- actor names
- movie titles
- country names
- vague praise words
- meaningless common words

Return useful phrases, preferably 2-4 words each.

Reviews:
{reviews_text}
"""

    response = client.models.generate_content(
        model="gemini-3.5-flash",
        contents=prompt,
        config={
            "temperature": 0.2,
            "response_mime_type": "application/json",
            "response_schema": KeywordResult,
        }
    )

    return response.parsed

def chunk_list(data, chunk_size=20):
    for i in range(0, len(data), chunk_size):
        yield data[i:i + chunk_size]

review_chunks = list(chunk_list(reviews, 20))

print(len(review_chunks))

all_phrases = []

for i, chunk in enumerate(review_chunks[:2]):

    print(f"\nProcessing chunk {i+1}...")

    try:

        result = extract_useful_phrases_with_gemini(chunk)

        print(result)

        for item in result.phrases:

            all_phrases.append({
                "phrase": item.phrase.lower().strip(),
                "category": item.category,
                "reason": item.reason
            })

    except Exception as e:

        import traceback
        traceback.print_exc()

phrases_df = pd.DataFrame(all_phrases)

phrases_df.head(20)

all_phrases = []

for i, chunk in enumerate(review_chunks):
    print(f"Processing chunk {i+1}/{len(review_chunks)}...")

    try:
        result = extract_useful_phrases_with_gemini(chunk)

        for item in result.phrases:
            all_phrases.append({
                "phrase": item.phrase.lower().strip(),
                "category": item.category,
                "reason": item.reason
            })

    except Exception as e:
        print(f"Error in chunk {i+1}: {e}")

phrases_df = pd.DataFrame(all_phrases)

phrases_df.head()

summary_df = (
    phrases_df
    .groupby(["phrase", "category"])
    .agg(
        count=("phrase", "size"),
        reason=("reason", "first")
    )
    .reset_index()
    .sort_values(by="count", ascending=False)
)

summary_df.head(30)

summary_df.to_excel("gemini_crime_movie_keyword_phrases.xlsx", index=False)

import pandas as pd

file_path = "bottom_10_crime_movies.xlsx"

df = pd.read_excel(file_path)

print(df.columns)
df.head()

reviews = df["Reviews"].dropna().astype(str).drop_duplicates().tolist()

print("Number of reviews:", len(reviews))

class KeywordPhrase(BaseModel):
    phrase: str = Field(
        description="A useful problem-related keyword phrase, preferably 2-4 words."
    )

    category: Literal[
        "genre_element",
        "story_element",
        "pacing",
        "suspense",
        "character",
        "acting",
        "realism",
        "emotion",
        "production",
        "audience_engagement",
        "hybrid_genre"
    ]

    reason: str = Field(
        description="Why this phrase is useful for understanding poor performance."
    )


class KeywordResult(BaseModel):
    phrases: List[KeywordPhrase]

def extract_useful_phrases_with_gemini(review_batch):

    reviews_text = "\n\n---\n\n".join(review_batch)

    prompt = f"""
You are a professional content analyst for a streaming company.

Task:
Extract useful keyword phrases from the following reviews of low-performing crime movies.

Focus on phrases that help explain why these movies performed poorly, especially:
- weak story elements
- poor pacing
- lack of suspense
- confusing plot structure
- weak character development
- poor acting / performance issues
- unrealistic scenes
- weak emotional engagement
- bad production quality
- audience disengagement
- failed genre expectations
- repetitive or predictable crime elements
- unsuccessful hybrid genre elements

Avoid:
- actor names
- movie titles
- country names
- vague negative words
- meaningless common words

Return useful problem-related phrases, preferably 2-4 words each.

Reviews:
{reviews_text}
"""

    response = client.models.generate_content(
        model="gemini-3.5-flash",
        contents=prompt,
        config={
            "temperature": 0.2,
            "response_mime_type": "application/json",
            "response_schema": KeywordResult,
        }
    )

    return response.parsed

def chunk_list(data, chunk_size=20):
    for i in range(0, len(data), chunk_size):
        yield data[i:i + chunk_size]


review_chunks = list(chunk_list(reviews, 20))

print("Number of chunks:", len(review_chunks))

all_phrases = []

for i, chunk in enumerate(review_chunks):
    print(f"Processing chunk {i+1}/{len(review_chunks)}...")

    try:
        result = extract_useful_phrases_with_gemini(chunk)

        for item in result.phrases:
            all_phrases.append({
                "phrase": item.phrase.lower().strip(),
                "category": item.category,
                "reason": item.reason
            })

    except Exception as e:
        print(f"Error in chunk {i+1}: {e}")

phrases_df = pd.DataFrame(all_phrases)

display(phrases_df.head())


summary_df = (
    phrases_df
    .groupby(["phrase", "category"])
    .agg(
        count=("phrase", "size"),
        reason=("reason", "first")
    )
    .reset_index()
    .sort_values(by="count", ascending=False)
)

display(summary_df.head(30))

output_path = "gemini_bottom10_crime_movie_keyword_phrases.xlsx"

summary_df.to_excel(output_path, index=False)

print(f"Saved to {output_path}")

